---
## AMD64 Docker Build
kind: pipeline
type: docker
name: amd64-build

platform:
  os: linux
  arch: amd64

steps:

- name: build-publish   
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: bgulla/rancher-demo
    auto_tag: true
    auto_tag_suffix: drone-build-amd64

---
## Docker Manifest Step- combines both architectures into a multi-tagged image. The docker client will pull the appropriate image based on the client's architecture.
kind: pipeline
name: default

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: bgulla/rancher-demo:latest
    template: bgulla/rancher-demo:drone-build-ARCH
    platforms:
      - linux/amd64
      # - linux/arm
depends_on:
- amd64-build
# - arm64-build

